04-testing-configuration-logging/01-unit-tests  - solution
js-tasks-ru/nodejs-20210907_anton-merezhko pull request #4
Opened 2021-10-01 09:27 UTC by antomer

2021-10-01 09:28 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-10-01 10:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2021-10-02 13:27 UTC, tadjik1 commented on 04-testing-configuration-logging/01-unit-tests/Validator.js
> +                error: `too big, expect ${rules.min}, got ${value}`,
кажется тут сообщение будет не совсем корректное, мы же проверяем на максимум

2021-10-02 13:28 UTC, tadjik1 requested changes
хорошая работа, заметил небольшую опечатку в проверке на максимум

2021-10-04 07:51 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-10-05 10:42 UTC, tadjik1 approved these changes

2021-10-05 10:42 UTC, merged